name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluiver:
    path: ../.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true
