name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  fluiver:
    path: ../.

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true
