name: fluiver
description: An expressive extensions and helpers package focused on productivity.
version: 1.0.1
homepage: https://mehmetesen.com

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  mockito: ^5.4.3
  rand: ^1.0.0
