name: fluiver
description: An un-opinionated, dependency free, expressive extensions package focused on productivity.
version: 1.0.0
homepage: https://mehmetesen.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  mockito:
  clock:
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
