name: fluiver
description: A dependency free, expressive extensions and helpers package focused on productivity.
version: 1.0.0
homepage: https://mehmetesen.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  mockito:
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
