name: fluiver
description: An un-opinionated, dependency free, expressive extensions package focused on productivity.
version: 0.0.1
homepage: https://mehmetesen.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.1.0
  build_runner: ^2.1.10
  clock: 1.1.0
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
