name: fluiver
description: An expressive extensions and helpers package focused on productivity.
version: 1.1.1
homepage: https://mehmetesen.com
repository: https://github.com/esenmx/fluiver

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mockito: ^5.4.4
  rand: ^2.0.2+2
