name: fluiver
description: An un-opinionated, dependency free, expressive extensions package focused on productivity.
version: 1.0.0
homepage: https://mehmetesen.com

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <3.0.0"
  mockito: ">=5.0.0 <6.0.0"
  clock: ">=1.0.0 <2.0.0"
  rand:
    git:
      url: https://github.com/esenmx/rand
      ref: main
